name: automotive_security_frontend
version: 1.0.0
publish_to: 'none'
description: Cross-platform automotive security app with BLE/Wi-Fi connectivity for RF signal monitoring.
author: Jonathan Marien <jon@chron0.tech>
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - mockups/

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.16.4
  wifi_iot: ^0.3.19+2
  flutter_local_notifications: ^19.2.0
  flutter_secure_storage: ^10.0.0-beta.4
  json_annotation: ^4.8.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.3.6
  equatable: ^2.0.5
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter

# End of pubspec.yaml
